### ISSUE TITLE
Android, authorization

### ISSUE THREAD

**Issue by firetix** [jpurcell/birdhouseapp#1]
Hi,

First thank you for your work.

I have an issue with birdhouse application on android in fact the authorization process fail when the popup shows asking if you want to remember password as you said :

"- On Android, on Twitter's authorization screen, if a popup shows asking if you want to remember this password, the authorization process may fail. If this is a confirmed issue, please post an issue ticket and we can resolve it."

Can you please give me a solution for this issue?

Thank you so much for you work.

Mohamed Rachidi.

**Comment by jpurcell** [comment]
I'm sorry, but currently I have not found a solution. If anyone does find a solution, please post it and I will incorporate it into the app.
